// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnumjclhyxmdwntfciif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudW1qY2xoeXhtZHdudGZjaWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDYxNTYsImV4cCI6MjA2MDEyMjE1Nn0.B1_UM2XTdS8fRWi53q88nKASqZw-po4Dzdi6Z4H9gN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);